/**
 * Mirror this repo's Claude Code agent assets into the Codex-readable
 * `.agents/skills/` tree so both CLIs get the same project behavior from one
 * source of truth.
 *
 *   SOURCE OF TRUTH  `.claude/agents/*.md`, `.claude/skills/<name>/**`
 *   GENERATED        `.agents/skills/<name>/**`  (committed; never hand-edit)
 *
 * Why this shape:
 *
 * - Codex discovers project skills at `<repo>/.agents/skills` and reads the same
 *   `SKILL.md` + YAML-frontmatter format Claude Code uses. Verified with
 *   `codex debug prompt-input`, which lists the repo's `.agents/skills` as a
 *   skill root. It does *not* read `.codex/skills` or `.codex/agents/*.toml`.
 * - Codex has no project-level subagent registry, so each Claude subagent is
 *   mirrored as a skill with a short "delegated role" preamble.
 * - Claude Code does not read `.agents/`, so the mirror has to be generated
 *   rather than shared. `.claude/` wins as the source because its format is the
 *   richer of the two (agents carry `tools:`/`model:`).
 *
 * Usage:
 *
 *   node --experimental-strip-types scripts/sync-agent-skills.ts           # write
 *   node --experimental-strip-types scripts/sync-agent-skills.ts --check   # verify only
 *   node --experimental-strip-types scripts/sync-agent-skills.ts --hook    # PostToolUse hook
 *
 * `--check` exits 1 on any drift and is what CI runs. `--hook` reads a Claude
 * Code hook payload on stdin, syncs only when a source file was touched, and
 * always exits 0 so it can never block a tool call.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

export const AGENT_SOURCE_DIR = '.claude/agents';
export const SKILL_SOURCE_DIR = '.claude/skills';
export const MIRROR_DIR = '.agents/skills';

/**
 * Marks a file as ours. Pruning only ever touches directories whose `SKILL.md`
 * carries this string, so hand-written Codex-only skills can live alongside the
 * generated ones without being deleted.
 */
export const GENERATED_MARKER = 'Generated by `npm run agents:sync`';

export type Frontmatter = { data: Record<string, string>; body: string };

/**
 * Minimal frontmatter reader for the flat `key: value` blocks these files use.
 * A line that does not start a new key is folded into the previous value, so a
 * wrapped description still round-trips.
 */
export function parseFrontmatter(source: string): Frontmatter {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(source);
  if (!match) return { data: {}, body: source.trim() };

  const data: Record<string, string> = {};
  let lastKey = '';
  for (const line of match[1].split(/\r?\n/)) {
    const keyed = /^([A-Za-z][\w-]*):\s?(.*)$/.exec(line);
    if (keyed) {
      lastKey = keyed[1];
      data[lastKey] = keyed[2].trim();
    } else if (lastKey && line.trim()) {
      data[lastKey] = `${data[lastKey]} ${line.trim()}`.trim();
    }
  }
  return { data, body: source.slice(match[0].length).trim() };
}

/** Quote a frontmatter value only when leaving it bare would change its meaning. */
export function yamlScalar(value: string): string {
  const needsQuotes = /^[\s#&*!|>%@`[\]{},'"]|:\s|\s#|:$/.test(value);
  if (!needsQuotes) return value;
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export function banner(sourceRel: string): string {
  return `<!-- ${GENERATED_MARKER} from ${sourceRel}. Edit that file, not this one. -->`;
}

/**
 * A skill mirrors verbatim — the format is identical in both CLIs — with only a
 * provenance banner inserted under the frontmatter.
 */
export function renderSkillMirror(source: string, sourceRel: string): string {
  const { data, body } = parseFrontmatter(source);
  const keys = Object.keys(data);
  if (keys.length === 0) return `${banner(sourceRel)}\n\n${body}\n`;

  const front = keys.map((k) => `${k}: ${yamlScalar(data[k])}`).join('\n');
  return `---\n${front}\n---\n\n${banner(sourceRel)}\n\n${body}\n`;
}

/**
 * A Claude subagent mirrors as a skill: Codex can spawn a subagent but has no
 * file-based registry for one, so the role's instructions are exposed as a skill
 * it can select. `tools:`/`model:` are dropped — they are Claude Code settings
 * with no Codex equivalent, and the preamble covers the tool-name mismatch.
 */
export function renderAgentMirror(source: string, sourceRel: string): string {
  const { data, body } = parseFrontmatter(source);
  const name = data.name ?? path.basename(sourceRel).replace(/\.md$/, '');
  const description = data.description ?? '';

  const preamble = [
    `> **Delegated role.** These are the instructions for the \`${name}\` role,`,
    `> mirrored from the Claude Code subagent at \`${sourceRel}\`. Run them in a`,
    '> subagent when you have one, otherwise follow them yourself for this turn.',
    "> Tool names below are Claude Code's — use your equivalents.",
  ].join('\n');

  return [
    '---',
    `name: ${yamlScalar(name)}`,
    `description: ${yamlScalar(description)}`,
    '---',
    '',
    banner(sourceRel),
    '',
    preamble,
    '',
    body,
    '',
  ].join('\n');
}

export type MirrorPlan = {
  /** Mirror directory name under `.agents/skills/`. */
  name: string;
  /** Source path, repo-relative and posix-separated. */
  sourceRel: string;
  /** Files to write, keyed by path relative to the mirror directory. */
  files: Map<string, Buffer>;
};

const toPosix = (p: string) => p.split(path.sep).join('/');
const read = (abs: string) => fs.readFileSync(abs);
const readText = (abs: string) => fs.readFileSync(abs, 'utf8');

function listFiles(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '.DS_Store') continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory())
      out.push(...listFiles(path.join(dir, entry.name), rel));
    else out.push(rel);
  }
  return out.sort();
}

/** Build the full expected mirror tree from the `.claude/` sources. */
export function plan(root: string = REPO_ROOT): MirrorPlan[] {
  const plans: MirrorPlan[] = [];

  const agentsDir = path.join(root, AGENT_SOURCE_DIR);
  if (fs.existsSync(agentsDir)) {
    for (const file of fs.readdirSync(agentsDir).sort()) {
      if (!file.endsWith('.md')) continue;
      const sourceRel = `${AGENT_SOURCE_DIR}/${file}`;
      const rendered = renderAgentMirror(
        readText(path.join(agentsDir, file)),
        sourceRel,
      );
      plans.push({
        name: file.replace(/\.md$/, ''),
        sourceRel,
        files: new Map([['SKILL.md', Buffer.from(rendered, 'utf8')]]),
      });
    }
  }

  const skillsDir = path.join(root, SKILL_SOURCE_DIR);
  if (fs.existsSync(skillsDir)) {
    for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const dir = path.join(skillsDir, entry.name);
      const skillFile = path.join(dir, 'SKILL.md');
      if (!fs.existsSync(skillFile)) continue;

      const sourceRel = `${SKILL_SOURCE_DIR}/${entry.name}/SKILL.md`;
      const files = new Map<string, Buffer>();
      for (const rel of listFiles(dir)) {
        files.set(
          rel,
          rel === 'SKILL.md'
            ? Buffer.from(
                renderSkillMirror(readText(skillFile), sourceRel),
                'utf8',
              )
            : read(path.join(dir, ...rel.split('/'))),
        );
      }
      plans.push({ name: entry.name, sourceRel, files });
    }
  }

  const seen = new Map<string, string>();
  for (const p of plans) {
    const clash = seen.get(p.name);
    if (clash) {
      throw new Error(
        `Mirror name collision: ${p.sourceRel} and ${clash} both map to ${MIRROR_DIR}/${p.name}`,
      );
    }
    seen.set(p.name, p.sourceRel);
  }

  return plans.sort((a, b) => a.name.localeCompare(b.name));
}

/** Mirror directories we own — i.e. ones a previous run generated. */
export function ownedDirs(root: string = REPO_ROOT): string[] {
  const mirrorRoot = path.join(root, MIRROR_DIR);
  if (!fs.existsSync(mirrorRoot)) return [];
  return fs
    .readdirSync(mirrorRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => {
      const skillFile = path.join(mirrorRoot, name, 'SKILL.md');
      return (
        fs.existsSync(skillFile) &&
        readText(skillFile).includes(GENERATED_MARKER)
      );
    })
    .sort();
}

export type Drift = {
  /** Expected file missing from the mirror. */
  missing: string[];
  /** Mirror file whose contents no longer match its source. */
  stale: string[];
  /** File inside a generated skill that the source no longer produces. */
  extra: string[];
  /** Generated skill whose source is gone. */
  orphaned: string[];
};

export function diff(root: string = REPO_ROOT, plans = plan(root)): Drift {
  const drift: Drift = { missing: [], stale: [], extra: [], orphaned: [] };
  const mirrorRoot = path.join(root, MIRROR_DIR);

  for (const p of plans) {
    const dir = path.join(mirrorRoot, p.name);
    for (const [rel, contents] of p.files) {
      const abs = path.join(dir, ...rel.split('/'));
      const target = `${MIRROR_DIR}/${p.name}/${rel}`;
      if (!fs.existsSync(abs)) drift.missing.push(target);
      else if (!read(abs).equals(contents)) drift.stale.push(target);
    }
    if (fs.existsSync(dir)) {
      for (const rel of listFiles(dir)) {
        if (!p.files.has(rel))
          drift.extra.push(`${MIRROR_DIR}/${p.name}/${rel}`);
      }
    }
  }

  const expected = new Set(plans.map((p) => p.name));
  for (const name of ownedDirs(root)) {
    if (!expected.has(name)) drift.orphaned.push(`${MIRROR_DIR}/${name}`);
  }

  return drift;
}

export function hasDrift(drift: Drift): boolean {
  return Object.values(drift).some((list) => list.length > 0);
}

/** Write the mirror and prune anything we own that the sources no longer produce. */
export function sync(root: string = REPO_ROOT): {
  written: string[];
  removed: string[];
} {
  const plans = plan(root);
  const mirrorRoot = path.join(root, MIRROR_DIR);
  const written: string[] = [];
  const removed: string[] = [];

  for (const p of plans) {
    const dir = path.join(mirrorRoot, p.name);
    fs.mkdirSync(dir, { recursive: true });

    for (const [rel, contents] of p.files) {
      const abs = path.join(dir, ...rel.split('/'));
      if (fs.existsSync(abs) && read(abs).equals(contents)) continue;
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, contents);
      written.push(`${MIRROR_DIR}/${p.name}/${rel}`);
    }

    // Drop leftovers from a source file that has since been deleted or renamed.
    for (const rel of listFiles(dir)) {
      if (p.files.has(rel)) continue;
      fs.rmSync(path.join(dir, ...rel.split('/')));
      removed.push(`${MIRROR_DIR}/${p.name}/${rel}`);
    }
  }

  const expected = new Set(plans.map((p) => p.name));
  for (const name of ownedDirs(root)) {
    if (expected.has(name)) continue;
    fs.rmSync(path.join(mirrorRoot, name), { recursive: true, force: true });
    removed.push(`${MIRROR_DIR}/${name}`);
  }

  return { written, removed };
}

/** True when a touched path could change the mirror. */
export function isSourcePath(
  filePath: string,
  root: string = REPO_ROOT,
): boolean {
  const normalized = toPosix(filePath).replace(/^\.\//, '');
  const rel = path.isAbsolute(filePath)
    ? toPosix(path.relative(root, filePath))
    : normalized;
  if (rel.startsWith('..')) return false;
  return (
    rel.startsWith(`${AGENT_SOURCE_DIR}/`) ||
    rel.startsWith(`${SKILL_SOURCE_DIR}/`) ||
    rel.startsWith(`${MIRROR_DIR}/`)
  );
}

function readStdin(): Promise<string> {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) return resolve('');
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => (data += chunk));
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', () => resolve(''));
  });
}

async function runHook(): Promise<void> {
  // Never fail a tool call: any problem here is reported, not thrown.
  try {
    const raw = await readStdin();
    if (raw.trim()) {
      const payload = JSON.parse(raw) as {
        tool_input?: { file_path?: string; path?: string };
      };
      const touched = payload.tool_input?.file_path ?? payload.tool_input?.path;
      if (touched && !isSourcePath(touched)) return;
    }
    const { written, removed } = sync();
    const changed = written.length + removed.length;
    if (changed > 0) {
      console.log(
        `agents:sync regenerated ${changed} file(s) under ${MIRROR_DIR} — commit them with the source change.`,
      );
    }
  } catch (error) {
    console.log(`agents:sync hook skipped: ${(error as Error).message}`);
  }
}

async function main(): Promise<void> {
  if (process.argv.includes('--hook')) {
    await runHook();
    return;
  }

  if (process.argv.includes('--check')) {
    const drift = diff();
    if (!hasDrift(drift)) {
      const count = plan().length;
      console.log(`${MIRROR_DIR} is in sync (${count} skills).`);
      return;
    }
    console.error(`${MIRROR_DIR} is out of sync with .claude/:`);
    for (const p of drift.missing) console.error(`  missing   ${p}`);
    for (const p of drift.stale) console.error(`  stale     ${p}`);
    for (const p of drift.extra) console.error(`  extra     ${p}`);
    for (const p of drift.orphaned) console.error(`  orphaned  ${p}`);
    console.error('\nRun `npm run agents:sync` and commit the result.');
    process.exit(1);
  }

  const { written, removed } = sync();
  const plans = plan();
  if (written.length === 0 && removed.length === 0) {
    console.log(`${MIRROR_DIR} already up to date (${plans.length} skills).`);
    return;
  }
  for (const p of written) console.log(`  wrote    ${p}`);
  for (const p of removed) console.log(`  removed  ${p}`);
  console.log(
    `Synced ${plans.length} skills into ${MIRROR_DIR} from .claude/agents and .claude/skills.`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1])
  void main();
