/// <reference path="../.astro/types.d.ts" />
/// <reference types="@cloudflare/vitest-pool-workers/types" />

// Astro-only declarations. Worker runtime and configured binding types come
// from the committed worker-configuration.d.ts generated by `npm run
// types:worker`; declarations both TypeScript programs need live in ambient.d.ts.

type Runtime = import('@astrojs/cloudflare').Runtime;
declare namespace App {
  interface Locals extends Runtime {
    authContext: import('./server/authz/guards').AuthContext | null;
    site: import('./lib/types').SiteSettings;
  }
}
